### ISSUE TITLE
Key combinations doesn't work in Firefox 52

### ISSUE THREAD

**Issue by manosnoam** [thePaulV/Most-Recent-Tab#5] opened 2017-12-14 13:55 UTC

**Comment by thePaulV** [comment] 2017-12-19 02:49
Hi, thanks for reporting this. I just tested in Firefox 57.0.1 running on Fedora 27; both keyboard shortcut and toolbar worked.

Can you provide the versions you were using, or any further information that might be helpful in tracking it down?

**Comment by thePaulV** [comment] 2018-01-14 21:17
Hi @manosnoam. I was not able to reproduce this bug. Closing for now, happy to reopen it if you can provide some more details on what versions of Fedora, Firefox and Most Recent Tab you were using.

**Comment by manosnoam** [comment] 2018-03-12 10:56
Hi @thePaulV 
It happens to me on RHEL 7.4 with  FF 52.6.0 (64-bit) - which is the latest supported version at the moment.
Ctrl + 1 and Command-shift-1 doesn't work. 
Can I change key combination to test other keys perhaps ?

**Comment by thePaulV** [comment] 2018-03-12 22:56
Thanks for the update @manosnoam. Looks like this probably broke when I added support for other addons to trigger the effect in v1.1. Testing a fix now.

**Comment by thePaulV** [comment] 2018-03-14 03:50
After investigating and testing with Firefox 52 ESR, I think it's actually related to [Firefox bug 1272198](https://bugzilla.mozilla.org/show_bug.cgi?id=1272198). [Comment 9](https://bugzilla.mozilla.org/show_bug.cgi?id=1272198#c9) in the bug suggests some combos that might work; I tested and confirmed that using Ctrl+Shift+F works.

Unfortunately there's no way to set the shortcut at runtime with the current Firefox APIs (see #1), but if you're comfortable building your own version of Most Recent Tab you can set Ctrl+Shift+F (or another working option) in manifest.json and you're good to go.

There's no general solution to this, so I'm closing as not fixable.

**Closed by thePaulV** 2018-03-14 03:50 UTC
Labels: bug

**Comment by manosnoam** [comment] 2018-04-03 10:30
What if I use an aditional plugin:
https://addons.mozilla.org/en-US/firefox/addon/shortkeys/

It has option to add javascript as shortkey. 
Is there an option to call your shortcutHit() from an external javascript ?

**Comment by manosnoam** [comment] 2018-04-03 11:58
Another plugin: https://addons.mozilla.org/en-US/firefox/addon/clut-cycle-last-used-tabs/

**Comment by thePaulV** [comment] 2018-05-08 02:11
@manosnoam: Yes, version 1.1 supports triggering this addon from other addons. [Here's how](https://gist.github.com/thePaulV/df47bb3a086f027f2301c662baf78e6a).

Also, Firefox 60 is supposed to be released this week, and it's an Extended Support Release version so hopefully you'll be able to upgrade on RHEL. That means a fix for the shortcut, plus support for setting your own using version 2.0.
